# Generated by Django 3.1.6 on 2021-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=100)),
                ('url', models.URLField(default='')),
                ('cap', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
